### ISSUE TITLE
Support messageCode and messageBody sample attributes

### ISSUE THREAD

**Issue by sheax0r** [heroku/refocus-ruby#1]
Currently you can't submit messageCode or messageBody attributes on samples. Enable this.

eg:
```json
{
  "messageBody": "75%",
  "messageCode": "75%",
  "value": "75"
},
```

**Comment by sheax0r** [comment]
I think ideally we would support this with optional named parameters on [the submit method](https://github.com/heroku/refocus-ruby/blob/db162bc032d2d2807f8575a27037314e63c50125/lib/refocus/samples.rb#L18). Like this:

```ruby
refocus.submit(
  name: "service",
  aspect: "availability", 
  value: 0.75, 
  message_body: "75%", 
  message_code: "75%")
```

**Comment by kkim-sf** [comment]
@sheax0r PR created to address this, but made a few more changes - https://github.com/heroku/refocus-ruby/pull/2
